### PR TITLE
update passport-oauth to 1.0.0

### PR DESCRIPTION
**Pull request by growlsworth**
addresses https://github.com/jaredhanson/passport/issues/400

tests pass on my local machine.

### CODE REVIEW

**Comment by romanmt** [comment]
Hey Growlsworth,

Thanks for the PR. Feel free to add yourself to the contributors list before I merge.

**Comment by growlsworth** [comment]
Thank romanmt. Done.

**Comment by growlsworth** [comment]
could you also update the npm package?

**Comment by jperkelens** [comment]
Done!

**Pull request merged**
